<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>gov.nsa.datawave.microservice</groupId>
        <artifactId>datawave-microservice-service-parent</artifactId>
        <version>5.0.7</version>
        <relativePath>../../microservice-service-parent/pom.xml</relativePath>
    </parent>
    <artifactId>spring-boot-starter-datawave-webservice</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <url>https://github.com/NationalSecurityAgency/datawave-spring-boot-starter-webservice</url>
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <scm>
        <connection>scm:git:${project.scm.url}</connection>
        <developerConnection>scm:git:${project.scm.url}</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.com/NationalSecurityAgency/datawave</url>
    </scm>
    <properties>
        <datawave.webservice.namespace>http://webservice.datawave/v1</datawave.webservice.namespace>
        <version.datawave>7.33.1</version.datawave>
        <version.datawave.starter>4.0.5</version.datawave.starter>
        <version.validation-api>2.0.2</version.validation-api>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>gov.nsa.datawave.core</groupId>
                <artifactId>datawave-core-connection-pool</artifactId>
                <version>${version.datawave}</version>
                <exclusions>
                    <exclusion>
                        <groupId>log4j</groupId>
                        <artifactId>log4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-reload4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>gov.nsa.datawave.microservice</groupId>
                <artifactId>spring-boot-starter-datawave</artifactId>
                <version>${version.datawave.starter}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>${version.validation-api}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>gov.nsa.datawave.core</groupId>
            <artifactId>datawave-core-connection-pool</artifactId>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>spring-boot-starter-datawave</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>github-datawave</id>
            <url>https://maven.pkg.github.com/NationalSecurityAgency/datawave</url>
        </repository>
    </repositories>
    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>source-templates/**</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-templated-sources</id>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <outputDirectory>${project.build.directory}/generated-sources/templated-sources</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/resources/source-templates</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <!-- This was added to ensure that nested test classes are run. -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <sources>
                                <source>target/generated-sources/templated-sources</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
